server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER_ADDRESS}/${MYSQL_DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    include:
      - jwt
      - oauth

redis:
  host: localhost
  port: 6379

#SMS 인증을 위한 api key
coolsms:
  apiKey: ${COOLSMS_API_KEY}
  apiSecret: ${COOLSMS_SECRET_KEY}
  senderNumber: ${COOLSMS_SENDER_NUMBER}

#로컬 파일업로드 경로
file:
  upload-dir: ${FILE_UPLOAD_DIR}