server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER_ADDRESS}/${MYSQL_DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    include:
      - jwt
      - oauth

  phone-authcode-expiration-millis: ${PHONE_AUTHCODE_EXPIRATION}
  
  # Redis 카카오페이 tid 유효 기간
  kakaopay-tid-expiration-millis: ${KAKAOPAY_TID_EXPIRATION} # 5 * 60 * 1000 == 5분

  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin
redis:
  host: ${REDIS_SERVER_ADDRESS}
  port: ${REDIS_SERVER_PORT}

#SMS 인증을 위한 api key
coolsms:
  apiKey: ${COOLSMS_API_KEY}
  apiSecret: ${COOLSMS_SECRET_KEY}
  senderNumber: ${COOLSMS_SENDER_NUMBER}

#전화번호 양방향 암호화 대칭키
symmetric:
  key: ${SYMMETRIC_KEY}
  salt: ${SYMMETRIC_SALT}

#로컬 파일업로드 경로
file:
  upload-dir: ${FILE_UPLOAD_DIR}

# 카카오페이 Secret Key
pay:
  secret-key: ${KAKAOPAY_SECERT_KEY}

# Redirect URL
redirectURL : http://localhost:8080